"""
Analysis summary is generated by Groq. It reads every Reddit post
and every YouTube comment we collected, then writes a simple, easy-to-understand summary.
Uses GROQ_API_KEY from your .env.
"""
import os
from typing import Dict

# Truncate each post/comment to this many characters so we can fit all of them in one request
MAX_CHARS_PER_ITEM = 220

# Safety cap: max total characters to send (avoids exceeding context)
MAX_TOTAL_CHARS = 95_000


def _gather_all_items(results: Dict) -> str:
    """Build one block of text with every Reddit post and every YouTube comment."""
    lines = []
    total_chars = 0
    platforms = results.get("platforms", {})

    for platform in ("reddit", "youtube"):
        pdata = platforms.get(platform)
        if not pdata:
            continue
        items = pdata.get("all_items") or pdata.get("sample_items") or []
        label = "Reddit posts" if platform == "reddit" else "YouTube comments"
        lines.append(f"\n--- {label} ({len(items)} items) ---\n")
        for item in items:
            if total_chars >= MAX_TOTAL_CHARS:
                lines.append("\n[... more items omitted to fit context ...]\n")
                break
            text = (item.get("text") or "").strip()
            if not text:
                continue
            if len(text) > MAX_CHARS_PER_ITEM:
                text = text[:MAX_CHARS_PER_ITEM] + "..."
            sent = item.get("sentiment", "neutral")
            line = f"[{sent}] {text}"
            lines.append(line)
            total_chars += len(line) + 1
        lines.append("")

    return "\n".join(lines) if lines else "No posts or comments available."


def generate_ai_summary(results: Dict, query: str) -> str | None:
    """
    Send every Reddit post and every YouTube comment to Groq. It analyzes each one
    and returns a simple, easy-to-understand summary. Uses GROQ_API_KEY.
    Returns None only if the API key is missing or the API call fails.
    """
    api_key = os.getenv("GROQ_API_KEY", "").strip()
    if not api_key:
        return None

    combined = results.get("combined", {})
    total = combined.get("total_items", 0)
    if total == 0:
        return None

    all_text = _gather_all_items(results)

    system_instruction = (
        "You are a clear, helpful writer. You will receive a list of real Reddit posts and YouTube comments about a product or topic.\n\n"
        "Your job:\n"
        "1. Read and consider every single post and comment.\n"
        "2. Write one short summary (150–200 words) that is simple and easy to understand.\n"
        "3. Say what people like, what they complain about, and what the overall takeaway is.\n"
        "4. Use plain language. No jargon. No bullet points or headings—just a few short paragraphs.\n"
        "5. Base everything only on what is in the posts and comments. Do not add facts from outside."
    )

    user_prompt = (
        f'Topic / product: "{query}"\n\n'
        "Below are ALL the Reddit posts and YouTube comments we collected. "
        "Each line is one post or comment. The label [positive], [neutral], or [negative] is our sentiment for that item.\n\n"
        "Analyze each and every one. Then write a simple, easy-to-understand summary for a general reader (150–200 words).\n\n"
        f"{all_text}\n\n"
        "Write the summary now. Simple and clear."
    )

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        model_name = os.getenv("GROQ_SUMMARY_MODEL", "llama-3.3-70b-versatile")

        response = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=550,
            temperature=0.3,
        )

        summary = (response.choices[0].message.content or "").strip()
        return summary if summary else None

    except Exception as e:
        err_msg = str(e).strip()
        print(f"Groq summary failed: {e}")

        if "404" in err_msg or "not found" in err_msg.lower():
            return (
                "Summary unavailable: Model not found. "
                "Set GROQ_SUMMARY_MODEL to a valid model (e.g. llama-3.3-70b-versatile) in .env and restart."
            )
        if "429" in err_msg or "quota" in err_msg.lower() or "rate_limit" in err_msg.lower():
            return "Summary unavailable: API quota/rate limit exceeded. Try again later or check your Groq plan."
        if "401" in err_msg or "403" in err_msg or "invalid" in err_msg.lower() or "api_key" in err_msg.lower():
            return "Summary unavailable: Check GROQ_API_KEY in .env."
        return f"Summary unavailable: {err_msg[:120]}."