from typing import Dict, List
from collections import Counter
import re
import os
import json
import html
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Thresholds: use same values for counting and labeling so UI matches stats
POSITIVE_THRESHOLD = 0.05
NEGATIVE_THRESHOLD = -0.05


class NLPProcessor:
    """Processes text data with NLP: sentiment analysis and keyword extraction"""
    
    def __init__(self):
        self.analyzer = SentimentIntensityAnalyzer()
    
    def process(self, data: Dict[str, List[Dict]], query: str) -> Dict:
        """Process all collected data and return analysis results"""
        results = {
            'query': query,
            'platforms': {},
            'combined': {
                'total_items': 0,
                'sentiment_counts': {'positive': 0, 'neutral': 0, 'negative': 0},
                'sentiment_scores': {'positive': 0.0, 'neutral': 0.0, 'negative': 0.0},
                'top_keywords': [],
                'summary': ''
            },
            'timestamp': None
        }
        
        # Process each platform
        for platform, items in data.items():
            if items:
                platform_result = self._process_platform(platform, items)
                results['platforms'][platform] = platform_result
                results['combined']['total_items'] += len(items)
        
        # Calculate combined statistics
        self._calculate_combined(results)
        
        # Summary is generated by Groq (analyzes every Reddit + YouTube item)
        from modules.ai_summary import generate_ai_summary
        ai_summary = generate_ai_summary(results, query)
        if ai_summary:
            results['combined']['summary'] = ai_summary
        else:
            results['combined']['summary'] = (
                "Summary could not be generated. Add GROQ_API_KEY to your backend .env and restart the server."
            )
        
        return results
    
    def _process_platform(self, platform: str, items: List[Dict]) -> Dict:
        """Process data from a single platform"""
        # Decode &#39; &amp; &gt; etc. from APIs (YouTube HTML, Reddit JSON)
        items = [
            {**it, "text": html.unescape((it.get("text") or "").strip()).strip()}
            for it in items
        ]

        sentiments = []
        all_text = []

        use_ai_sentiment = (os.getenv("USE_AI_SENTIMENT", "true").lower() == "true")
        ai_labels = self._get_ai_sentiment_labels(items) if use_ai_sentiment else None
        
        for item in items:
            text = item.get('text', '')
            if text:
                all_text.append(text)
                normalized = self._normalize_text_for_sentiment(text)
                base = self.analyzer.polarity_scores(normalized)
                adjusted = self._adjust_sentiment_for_domain(text, base)
                sentiments.append(adjusted)

        # If AI labels are available, align score objects to AI output for better accuracy.
        if ai_labels and len(ai_labels) == len(sentiments):
            sentiments = [self._scores_from_label(lbl) for lbl in ai_labels]
        
        # Count sentiments (same thresholds as labels so stats match UI)
        pos_count = sum(1 for s in sentiments if s['compound'] > POSITIVE_THRESHOLD)
        neu_count = sum(1 for s in sentiments if NEGATIVE_THRESHOLD <= s['compound'] <= POSITIVE_THRESHOLD)
        neg_count = sum(1 for s in sentiments if s['compound'] < NEGATIVE_THRESHOLD)
        
        # Calculate average scores
        avg_positive = sum(s['pos'] for s in sentiments) / len(sentiments) if sentiments else 0
        avg_neutral = sum(s['neu'] for s in sentiments) / len(sentiments) if sentiments else 0
        avg_negative = sum(s['neg'] for s in sentiments) / len(sentiments) if sentiments else 0
        
        # Extract keywords
        keywords = self._extract_keywords(' '.join(all_text))
        
        # Get sample items with sentiment (for display)
        sample_items = []
        for i, item in enumerate(items[:5]):  # Top 5 samples
            if i < len(sentiments):
                sentiment_label = self._get_sentiment_label(sentiments[i]['compound'])
                sample_items.append({
                    'text': item.get('text', '')[:200],  # Truncate long text
                    'sentiment': sentiment_label,
                    'score': sentiments[i]['compound'],
                    **{k: v for k, v in item.items() if k != 'text'}
                })
        
        # Get all items with sentiment (for keyword filtering)
        all_items = []
        for i, item in enumerate(items):
            if i < len(sentiments):
                sentiment_label = self._get_sentiment_label(sentiments[i]['compound'])
                all_items.append({
                    'text': item.get('text', ''),
                    'sentiment': sentiment_label,
                    'score': sentiments[i]['compound'],
                    **{k: v for k, v in item.items() if k != 'text'}
                })
        
        return {
            'total': len(items),
            'sentiment_counts': {
                'positive': pos_count,
                'neutral': neu_count,
                'negative': neg_count
            },
            'sentiment_scores': {
                'positive': round(avg_positive, 3),
                'neutral': round(avg_neutral, 3),
                'negative': round(avg_negative, 3)
            },
            'top_keywords': keywords[:10],
            'sample_items': sample_items,
            'all_items': all_items  # Include all items for filtering
        }
    
    def _extract_keywords(self, text: str) -> List[str]:
        """Extract keywords from text"""
        # Simple keyword extraction: remove common words and get frequent terms
        # Remove special characters and convert to lowercase
        text = re.sub(r'[^\w\s]', '', text.lower())
        
        # Common stop words
        stop_words = {
            'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
            'of', 'with', 'by', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
            'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'should',
            'could', 'may', 'might', 'must', 'can', 'this', 'that', 'these', 'those',
            'i', 'you', 'he', 'she', 'it', 'we', 'they', 'my', 'your', 'his', 'her',
            'its', 'our', 'their', 'me', 'him', 'us', 'them', 'what', 'which', 'who',
            'when', 'where', 'why', 'how', 'all', 'each', 'every', 'both', 'few',
            'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only',
            'own', 'same', 'so', 'than', 'too', 'very', 'just', 'now'
        }
        
        # Split into words and filter
        words = [w for w in text.split() if len(w) > 3 and w not in stop_words]
        
        # Count frequency
        word_counts = Counter(words)
        
        # Return top keywords
        return [word for word, count in word_counts.most_common(20)]
    
    def _get_sentiment_label(self, compound_score: float) -> str:
        """Get sentiment label from compound score (same thresholds as counts)."""
        if compound_score > POSITIVE_THRESHOLD:
            return 'positive'
        elif compound_score < NEGATIVE_THRESHOLD:
            return 'negative'
        return 'neutral'

    def _normalize_text_for_sentiment(self, text: str) -> str:
        """Light normalization so VADER is more consistent (repeated punctuation, spacing)."""
        if not text or not text.strip():
            return text
        # Collapse repeated ! and ? to single (VADER can over-weight !!!)
        t = re.sub(r'!+', '!', text)
        t = re.sub(r'\?+', '?', t)
        return t.strip()

    def _adjust_sentiment_for_domain(self, text: str, scores: Dict[str, float]) -> Dict[str, float]:
        """
        Domain-specific adjustments for product reviews (phones, laptops, gadgets)
        on top of VADER. Handles negations and review-specific phrases.
        """
        lowered = text.lower()
        compound = scores.get('compound', 0.0)

        # ----- Negation handling (VADER misses some in long text) -----
        negations_positive = [
            "not bad", "isn't bad", "wasn't bad", "not terrible", "not the worst",
            "no issues", "no issue", "no problems", "no problem", "no lag",
            "no heating", "no complaints", "nothing wrong", "don't regret",
            "can't complain", "couldn't be happier", "not disappointed",
        ]
        negations_negative = [
            "not good", "isn't good", "wasn't good", "not great", "not worth",
            "don't recommend", "wouldn't recommend", "can't recommend",
            "not recommended", "not satisfied", "not happy", "not worth it",
            "nothing good", "no good", "not impressed", "not worth the money",
        ]
        if any(p in lowered for p in negations_positive):
            compound += 0.25
        if any(p in lowered for p in negations_negative):
            compound -= 0.3

        # ----- Strong negative: product issues -----
        strong_neg = [
            "overheat", "overheating", "heating issue", "heats a lot", "gets hot",
            "lag", "laggy", "lags", "stutter", "stuttering", "frame drop", "hangs",
            "battery drain", "battery is bad", "poor battery", "bad battery",
            "worst camera", "camera is bad", "terrible camera", "useless",
            "waste of money", "waste of time", "regret buying", "returned it",
            "defective", "broken", "crashes", "crash", "freezes", "freeze",
            "unusable", "disappointed", "disappointing", "horrible", "garbage",
            "trash", "overpriced", "not worth the price", "slow", "too slow",
            "bloatware", "ads", "too many ads", "fingerprint issue", "face unlock fail",
        ]
        # Single-word or short negative boosts
        for p in strong_neg:
            if p in lowered:
                compound -= 0.22
                break  # avoid double-penalizing

        # ----- Strong positive: satisfaction and recommendation -----
        strong_pos = [
            "battery life is great", "battery backup is great", "amazing battery",
            "camera is great", "camera is awesome", "camera is excellent",
            "very smooth", "super smooth", "no lag", "handles gaming well",
            "love it", "loving it", "best purchase", "worth every penny",
            "highly recommend", "strongly recommend", "would recommend",
            "great value", "best value", "excellent value", "no complaints",
            "perfect for", "exactly what i wanted", "exceeded expectations",
            "build quality is", "display is great", "screen is amazing",
        ]
        for p in strong_pos:
            if p in lowered:
                compound += 0.2
                break

        # ----- Moderate positive/negative words (review context) -----
        mod_pos_words = {"recommend", "worth", "satisfied", "smooth", "reliable", "solid"}
        mod_neg_words = {"disappoint", "lag", "overheat", "drain", "bug", "glitch", "defect"}
        words = set(re.findall(r"[a-z]+", lowered))
        if words & mod_pos_words and compound > 0:
            compound += 0.08
        if words & mod_neg_words and compound < 0:
            compound -= 0.08

        compound = max(-1.0, min(1.0, compound))
        adjusted = dict(scores)
        adjusted['compound'] = compound
        return adjusted
    
    def _calculate_combined(self, results: Dict):
        """Calculate combined statistics across all platforms"""
        total_pos = sum(p['sentiment_counts']['positive'] for p in results['platforms'].values())
        total_neu = sum(p['sentiment_counts']['neutral'] for p in results['platforms'].values())
        total_neg = sum(p['sentiment_counts']['negative'] for p in results['platforms'].values())
        
        results['combined']['sentiment_counts'] = {
            'positive': total_pos,
            'neutral': total_neu,
            'negative': total_neg
        }
        
        # Calculate weighted average scores
        total_items = results['combined']['total_items']
        if total_items > 0:
            avg_pos = sum(
                p['sentiment_scores']['positive'] * p['total']
                for p in results['platforms'].values()
            ) / total_items
            
            avg_neu = sum(
                p['sentiment_scores']['neutral'] * p['total']
                for p in results['platforms'].values()
            ) / total_items
            
            avg_neg = sum(
                p['sentiment_scores']['negative'] * p['total']
                for p in results['platforms'].values()
            ) / total_items
            
            results['combined']['sentiment_scores'] = {
                'positive': round(avg_pos, 3),
                'neutral': round(avg_neu, 3),
                'negative': round(avg_neg, 3)
            }
        
        # Combine keywords from all platforms
        all_keywords = []
        for platform_data in results['platforms'].values():
            all_keywords.extend(platform_data.get('top_keywords', []))
        
        keyword_counts = Counter(all_keywords)
        results['combined']['top_keywords'] = [
            word for word, count in keyword_counts.most_common(15)
        ]

    def _scores_from_label(self, label: str) -> Dict[str, float]:
        """Convert sentiment label to VADER-like score object for UI compatibility."""
        if label == "positive":
            return {"neg": 0.0, "neu": 0.15, "pos": 0.85, "compound": 0.6}
        if label == "negative":
            return {"neg": 0.85, "neu": 0.15, "pos": 0.0, "compound": -0.6}
        return {"neg": 0.0, "neu": 1.0, "pos": 0.0, "compound": 0.0}

    def _get_ai_sentiment_labels(self, items: List[Dict]) -> List[str] | None:
        """
        AI sentiment classification for better context handling.
        Returns one label per input item in same order, or None to fallback to VADER.
        """
        texts = [(item.get("text") or "").strip() for item in items]
        if not texts:
            return None

        groq_key = (os.getenv("GROQ_API_KEY") or "").strip()
        if groq_key:
            labels = self._classify_with_groq(texts, groq_key)
            if labels:
                return labels

        return None

    def _classify_with_groq(self, texts: List[str], api_key: str) -> List[str] | None:
        try:
            from groq import Groq

            client = Groq(api_key=api_key)
            model = os.getenv(
                "GROQ_SENTIMENT_MODEL",
                os.getenv("GROQ_SUMMARY_MODEL", "llama-3.3-70b-versatile"),
            )
            batch_size = int(os.getenv("GROQ_SENTIMENT_BATCH_SIZE", "30"))
            final_labels: List[str] = []

            for i in range(0, len(texts), batch_size):
                batch = texts[i:i + batch_size]
                payload = [{"id": idx, "text": t[:900]} for idx, t in enumerate(batch)]
                prompt = (
                    "Classify each text sentiment for product feedback.\n"
                    "Use exactly one label: positive, neutral, or negative.\n"
                    "Return ONLY valid JSON array like:\n"
                    "[{\"id\":0,\"sentiment\":\"positive\"},{\"id\":1,\"sentiment\":\"neutral\"}]\n\n"
                    f"Items:\n{json.dumps(payload, ensure_ascii=True)}"
                )

                resp = client.chat.completions.create(
                    model=model,
                    temperature=0,
                    max_tokens=1200,
                    messages=[
                        {
                            "role": "system",
                            "content": "You are a strict sentiment classifier. Output only JSON.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                )

                content = (resp.choices[0].message.content or "").strip() if resp.choices else ""
                if not content:
                    return None
                # Remove markdown fence if present
                content = content.replace("```json", "").replace("```", "").strip()
                arr = json.loads(content)
                if not isinstance(arr, list):
                    return None

                labels_by_id = {}
                for row in arr:
                    if not isinstance(row, dict):
                        continue
                    rid = row.get("id")
                    s = str(row.get("sentiment", "")).lower().strip()
                    if s not in {"positive", "neutral", "negative"}:
                        s = "neutral"
                    if isinstance(rid, int):
                        labels_by_id[rid] = s

                for idx in range(len(batch)):
                    final_labels.append(labels_by_id.get(idx, "neutral"))

            return final_labels if len(final_labels) == len(texts) else None
        except Exception:
            return None
    
